if( typeof WBBLANG == 'undefined' ) WBBLANG = {};

WBBLANG['ru'] = {
	bold: "Полужирный",
	italic: "Курсив",
	underline: "Подчеркнутый",
	strike: "Зачеркнутый",
	link: "Ссылка",
	img: "Изображение",
	sup: "Надстрочный текст",
	sub: "Подстрочный текст",
	justifyleft: "Текст по левому краю",
	justifycenter: "Текст по центру",
	justifyright: "Текст по правому краю",
	justify: "Текст по ширине",
	bullist: "Маркированный список",
	quote: "Цитата",
	code: "Код",
	spoiler: "Спойлер",
	spoilerText: "Скрыть/показать спойлер",
	fontcolor: "Цвет текста",
	fontsize: "Размер шрифта",
	fontfamily: "Шрифт",
	smilebox: "Вставить смайл",
	video: "Вставить видео",
	modal_link_title: "Вставить ссылку",
	modal_link_text: "Отображаемый текст",
	modal_link_url: "URL ссылки",
	modal_email_text: "Отображаемый эл.адрес",
	modal_email_url: "Email",
	modal_link_tab1: "Вставить URL",
	modal_img_title: "Вставить изображение",
	modal_img_tab1: "Ввести URL",
	modal_img_tab2: "Загрузить",
	modal_imgsrc_text: "Введите адрес изображения",
	modal_video_text: "Введите URL видео на YouTube:",
	close: "Закрыть",
	save: "Сохранить",
	cancel: "Отмена",
	remove: "Удалить",
	validation_err: "Введенные данные некорректны",
	loading: "Загрузка",
	auto: "Авто",
	hr: "Горизонтальная линия",
	br: "Перевод строки",
	hideShort: "Скрытый текст",
	hide: "Скрытый текст (для незарегистрированных)",
	video_url_error: "Неправильный URL видео",
	link_text_error: "Не задан текст ссылки",
	link_url_error: "Неправильный URL",
	img_src_error: "Неправильный URL изображения",
	smiles_additional: "Больше смайлов...",
	separator: "Разделитель",
	mode_switch_button: "Режим BB кодов",
	select_text_for_quote: "Выделите текст для цитирования",
	uImageWidth: "Ширина изображения",
	uImageHeight: "Высота изображения",
	uImageInsert: "Вставить в редактор",
	uImageRemove: "Удалить"
};

UWBBLANG = WBBLANG['ru'];
